version: "3.9"
volumes: 
    shouko:
services:
  bot-service:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./
    environment: 
        MONGO_USERNAME: root
        MONGO_PASSWORD: localhost
    depends_on: 
        - mongo
  mongo:
    restart: always
    image: mongo
    volumes: 
        - shouko:/data/db