const discord = require('discord.js')
const { token, topgg } = require('./config.json')
const client = new discord.Client()
const dbl = require('dblapi.js')
const DBL = new dbl(topgg, client)
require('./functions/func.js')(client)
require('./functions/events.js')(client)
client.login(token)
